services:
  basic_rails_web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: basic_rails_web
    image: basic_rails_web:0.1
    command: bash -c "bundle exec rake db:create && bundle exec rake db:migrate && ./bin/rails server -b 0.0.0.0 -p 3000"
    ports:
      - "3000:3000"
    networks:
      - basic_rails_network
    volumes:
      - ./:/rails

networks:
  basic_rails_network:
    external: true